crash-digger: drop logging, daemon, and infinite loop, just use single-shot; also adapt stdout/stderr reporting to be suitable for cron and redirecting stdout to a log file.
Adapt test-crash-digger accordingly.

See https://wiki.ubuntu.com/DesktopTeam/Specs/Jaunty/ApportRetracerMaintenance

diff --git a/test-crash-digger b/test-crash-digger
--- a/test-crash-digger
+++ b/test-crash-digger
@@ -21,10 +21,10 @@ databases = { 'memory': {
 
         self.apport_chroot_log = os.path.join(self.workdir, 'apport-chroot.log')
 
-        apport_chroot = os.path.join(self.workdir, 'apport-chroot')
-        open(apport_chroot, 'w').write('''#!/bin/sh
+        self.apport_chroot = os.path.join(self.workdir, 'apport-chroot')
+        open(self.apport_chroot, 'w').write('''#!/bin/sh
 echo "$@" >> %s''' % self.apport_chroot_log)
-        os.chmod(apport_chroot, 0755)
+        os.chmod(self.apport_chroot, 0755)
 
         os.environ['APPORT_CRASHDB_CONF'] = crashdb_conf
         os.environ['PYTHONPATH'] = '.'
@@ -33,91 +33,82 @@ echo "$@" >> %s''' % self.apport_chroot_log)
     def tearDown(self):
         shutil.rmtree(self.workdir)
 
-    def call(self, args, timeout=None):
-        '''Call crash-digger with given arguments, terminate it after given
-        number of seconds, and return a pair (stdout, stderr).'''
-
+    def call(self, args):
+        '''Call crash-digger with given arguments.
+        
+        Return a pair (stdout, stderr).
+        '''
         out = tempfile.TemporaryFile()
         err = tempfile.TemporaryFile()
-        s = subprocess.Popen(['crash-digger'] + args, stdout=out, stderr=err)
-        if timeout:
-            time.sleep(timeout)
-            self.assertEqual(s.poll(), None, 'crash-digger is still running')
-            os.kill(s.pid, signal.SIGTERM)
-        s.wait()
+        s = subprocess.call(['crash-digger'] + args, stdout=out, stderr=err)
         out.seek(0)
         err.seek(0)
         return (out.read(), err.read())
 
-    def test_foreground_nopython(self):
-        '''Test operation in foreground without -i'''
+    def test_crashes(self):
+        '''Test crash retracing.'''
 
         (out, err) = self.call(['-m', self.chroot_map, '-a', '/dev/zero', '-d',
-            os.path.join(self.workdir, 'dup.db'), '-vs1'], timeout=2)
+            os.path.join(self.workdir, 'dup.db'), '-v'])
         self.assertEqual(err, '', 'no error messages')
         self.assert_("Available releases: ['Testux 1.0', 'Testux 2.2']" in out)
+        self.assert_('retracing #0' in out)
+        self.assert_('retracing #1' in out)
+        self.assert_('retracing #2' in out)
         self.assert_('crash is release FooLinux Pi/2 which does not have a chroot available' in out)
-        self.assert_('retracing #1 exit status: 0' in out)
-        self.assert_('retracing #2 exit status: 0' in out)
-        self.assert_('fill_pool: fail pool now: set([0])' in out)
-        self.assert_('#3' not in out, 'Python crashes are not retraced')
+        self.failIf('failed with status' in out)
+        self.failIf('#3' in out, 'dupcheck crashes are not retraced')
+        self.failIf('#4' in out, 'dupcheck crashes are not retraced')
 
-    def test_foreground_python(self):
-        '''Test operation in foreground with -i'''
+        chroot_log = open(self.apport_chroot_log).read()
+        self.assert_('retrace 1\n' in chroot_log)
+        self.assert_('retrace 2\n' in chroot_log)
+
+    def test_crashes_error(self):
+        '''Test crash retracing if apport-chroot fails on bug #1.'''
+
+        # make apport-retrace fail on bug 1
+        open(self.apport_chroot, 'w').write('''#!/bin/sh
+echo "$@" >> %s
+while [ -n "$2" ]; do shift; done
+if [ "$1" = 1 ]; then
+    echo "cannot frobnicate chroot" >&2
+    exit 1
+fi
+''' % self.apport_chroot_log)
 
         (out, err) = self.call(['-m', self.chroot_map, '-a', '/dev/zero', '-d',
-            os.path.join(self.workdir, 'dup.db'), '-vis1'], timeout=2)
+            os.path.join(self.workdir, 'dup.db'), '-v'])
+        self.assert_('Traceback' in err)
+        self.assert_('SystemError: retracing #1 failed' in err)
+        self.assert_("Available releases: ['Testux 1.0', 'Testux 2.2']" in out)
+        self.assert_('retracing #0' in out)
+        self.assert_('retracing #1' in out)
+        self.failIf('retracing #2' in out, 'should not continue after errors')
+        self.assert_('crash is release FooLinux Pi/2 which does not have a chroot available' in out)
+        self.failIf('#0 failed with status' in out)
+        self.assert_('#1 failed with status: 1' in out)
+        self.failIf('#3' in out, 'dupcheck crashes are not retraced')
+        self.failIf('#4' in out, 'dupcheck crashes are not retraced')
+
+        chroot_log = open(self.apport_chroot_log).read()
+        self.assert_('retrace 1\n' in chroot_log)
+        self.failIf('retrace 2\n' in chroot_log)
+
+    def test_dupcheck(self):
+        '''Test duplicate checking.'''
+
+        (out, err) = self.call(['-m', self.chroot_map, '-a', '/dev/zero', '-d',
+            os.path.join(self.workdir, 'dup.db'), '-vD'])
         self.assertEqual(err, '', 'no error messages')
         self.assert_("Available releases: ['Testux 1.0', 'Testux 2.2']" in out)
-        self.assert_('crash is release FooLinux Pi/2 which does not have a chroot available' in out)
-        self.assert_('retracing #1 exit status: 0' in out)
-        self.assert_('retracing #2 exit status: 0' in out)
-        self.assert_('fill_pool: fail pool now: set([0])' in out)
+        self.failIf('#1' in out, 'signal crashes are not retraced')
+        self.failIf('#2' in out, 'signal crashes are not retraced')
         self.assert_('checking #3 for duplicate' in out)
         self.assert_('checking #4 for duplicate' in out)
         self.assert_('Report is a duplicate of #3 (not fixed yet)' in out)
+        self.failIf(os.path.exists(self.apport_chroot_log))
 
-    def test_daemon(self):
-        '''Test operation in daemon mode'''
-
-        log = tempfile.NamedTemporaryFile()
-        (fd, pidfile) = tempfile.mkstemp()
-        os.close(fd)
-
-        try:
-            (out, err) = self.call(['-m', self.chroot_map, '-a', '/dev/zero', '-d',
-                os.path.join(self.workdir, 'dup.db'), '-vs1', '-l', log.name,
-                '-p', pidfile])
-            self.assertEqual(err, '', 'no error messages: ' + err)
-            self.assertEqual(out, '', 'no output messages: ' + out)
-            # let it grind for a while and then shut it down
-            time.sleep(2)
-            (out, err) = self.call(['--stop', '-p', pidfile])
-            self.assertEqual(err, '', 'no error messages')
-
-            log.seek(0)
-            out = log.read()
-            self.assert_("Available releases: ['Testux 1.0', 'Testux 2.2']" in out)
-            self.assert_('crash is release FooLinux Pi/2 which does not have a chroot available' in out)
-            self.assert_('retracing #1 exit status: 0' in out)
-            self.assert_('retracing #2 exit status: 0' in out)
-            self.assert_('fill_pool: fail pool now: set([0])' in out)
-            self.assert_('#3' not in out, 'Python crashes are not retraced')
-        finally:
-            os.unlink(pidfile)
-
-    def test_daemon_exception(self):
-        '''Test exception logging in daemon mode'''
-
-        log = tempfile.NamedTemporaryFile()
-
-        (out, err) = self.call(['-m', '/etc/passwd', '-a', '/dev/zero', '-vs1',
-            '-l', log.name, '-p', '/dev/null'])
-        self.assertEqual(err, '', 'no error messages: ' + err)
-        self.assertEqual(out, '', 'no output messages: ' + out)
-        log.seek(0)
-        out = log.read()
-        self.assert_('SyntaxError' in out)
 
 tl = unittest.TestLoader()
 tests_all = unittest.TestSuite((
